# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# build-client pipeline

name: $(Build.BuildId)

parameters:
- name: releaseBuildOverride
  displayName: Release Build (default = not released)
  type: string
  default: none
  values:
    - none
    - prerelease
    - release
- name: publishOverride
  displayName: Publish Override (default = based on branch)
  type: string
  default: default
  values:
    - default
    - skip
    - force
- name: buildToolsVersionToInstall
  displayName: Fluid build tools version (default = installs version in repo)
  type: string
  default: "^0.55.0"
- name: nonScopedPackages
  displayName: Non-scoped packages to publish
  type: object
  default:
  - fluid-framework
# The semver range constraint to use for interdependencies; that is, dependencies on other packages within the release
# group
- name: interdependencyRange
  type: string
  default: "^"

trigger:
  branches:
    include:
    - main
    - next
    - lts
    - release/*
  paths:
    include:
    - packages
    - examples
    - experimental
    - package.json
    - package-lock.json
    - pnpm-lock.json
    - pnpm-workspace.yaml
    - tools/pipelines/build-client.yml
    - tools/pipelines/scripts/build-version.js
    - tools/pipelines/templates/build-npm-package.yml
    - tools/pipelines/templates/include-set-package-version.yml
    - tools/pipelines/templates/include-vars.yml
    - tools/pipelines/templates/include-install-pnpm.yml
    - tools/pipelines/templates/include-publish-npm-package.yml
    - tools/pipelines/templates/include-publish-npm-package-deployment.yml
    - tools/pipelines/templates/include-publish-npm-package-steps.yml
    - tools/pipelines/templates/include-git-tag-steps.yml

pr:
  branches:
    include:
    - main
    - next
    - lts
    - release/*
  paths:
    include:
    - packages
    - examples
    - experimental
    - package.json
    - package-lock.json
    - pnpm-lock.json
    - pnpm-workspace.yaml
    - tools/pipelines/build-client.yml
    - tools/pipelines/scripts/build-version.js
    - tools/pipelines/templates/build-npm-package.yml
    - tools/pipelines/templates/include-set-package-version.yml
    - tools/pipelines/templates/include-vars.yml
    - tools/pipelines/templates/include-install-pnpm.yml

schedules:
- cron: "00 09 * * *" # every day at 9:00 UTC
  displayName: Daily LTS build
  branches:
    include:
    - lts
  always: true

variables:
  - template: /tools/pipelines/templates/include-vars.yml@self
    parameters:
      publishOverride: '${{ parameters.publishOverride }}'
      releaseBuildOverride: '${{ parameters.releaseBuildOverride }}'

extends:
  template: templates/build-npm-package.yml@self
  parameters:
    publishOverride: ${{ parameters.publishOverride }}
    releaseBuildOverride: ${{ parameters.releaseBuildOverride }}
    nonScopedPackages: ${{ parameters.nonScopedPackages }}
    buildToolsVersionToInstall: ${{ parameters.buildToolsVersionToInstall }}
    buildDirectory: .
    tagName: client
    poolBuild: Large-eastus2
    cgSubDirectory: packages
    checkoutSubmodules: true
    taskBundleAnalysis: true